create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  description text not null default '',
  publication_year integer not null,
  isbn text not null default '',
  cover_url text not null default '',
  purchase_url text not null default '',
  published boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_books_publicados on public.books (published, publication_year desc);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  protocol text not null unique,
  author_name text not null,
  email text not null,
  phone text not null default '',
  biography text not null,
  title text not null,
  subtitle text not null default '',
  category text not null,
  synopsis text not null,
  audience text not null,
  differentiator text not null,
  stage text not null,
  word_count text not null default '',
  rights_confirmed boolean not null check (rights_confirmed = true),
  cover_available boolean not null default false,
  reviewer_one text not null default '',
  reviewer_two text not null default '',
  notes text not null default '',
  status text not null default 'recebida',
  created_at timestamptz not null default now()
);
create index if not exists idx_submissions_status_data on public.submissions (status, created_at desc);

alter table public.books enable row level security;
alter table public.submissions enable row level security;
drop policy if exists "catalogo_publico_leitura" on public.books;
create policy "catalogo_publico_leitura" on public.books for select to anon using (published = true);
drop policy if exists "propostas_publicas_insercao" on public.submissions;
create policy "propostas_publicas_insercao" on public.submissions for insert to anon with check (rights_confirmed = true and status = 'recebida');

grant select on public.books to anon;
grant insert on public.submissions to anon;
revoke select, update, delete on public.submissions from anon;

-- Formulário editorial completo (modelo oficial de submissão)
create table if not exists public.editorial_submissions (
  id bigint generated by default as identity primary key,
  protocol text not null unique,
  scope_confirmed boolean not null check (scope_confirmed = true),
  author_name text not null,
  email text not null,
  phone text not null,
  institution text not null,
  department text not null,
  cine_areas text not null,
  work_authors text not null,
  work_type text not null,
  page_count integer not null check (page_count > 0),
  relevance text not null,
  originality text not null,
  reach text not null,
  collection_fit text not null,
  work_title text not null,
  presentation text not null,
  table_of_contents text not null,
  audiences text not null,
  editorial_fit text not null,
  neurolearning text not null default '',
  visual_identity text not null,
  reviewer_one text not null,
  reviewer_two text not null,
  manuscript_path text not null,
  rights_file_path text not null,
  rights_confirmed boolean not null check (rights_confirmed = true),
  status text not null default 'recebida',
  created_at timestamptz not null default now()
);
create index if not exists idx_editorial_submissions_status_data on public.editorial_submissions (status, created_at desc);
alter table public.editorial_submissions enable row level security;
drop policy if exists "propostas_editoriais_insercao" on public.editorial_submissions;
create policy "propostas_editoriais_insercao" on public.editorial_submissions for insert to anon
with check (scope_confirmed = true and rights_confirmed = true and status = 'recebida');
grant insert on public.editorial_submissions to anon;
revoke select, update, delete on public.editorial_submissions from anon;

-- Bucket privado: somente a equipe autenticada poderá consultar os originais.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'editorial-submissions',
  'editorial-submissions',
  false,
  1073741824,
  array[
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/pdf'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "upload_publico_propostas_editoriais" on storage.objects;
create policy "upload_publico_propostas_editoriais" on storage.objects for insert to anon
with check (bucket_id = 'editorial-submissions');
