export {default} from "./site";
"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,FileText,Search,Sparkles} from "lucide-react";
import {Button} from "@/components/ui/button"; import {Card} from "@/components/ui/card"; import {Checkbox} from "@/components/ui/checkbox"; import {Input} from "@/components/ui/input"; import {NativeSelect} from "@/components/ui/native-select"; import {Progress} from "@/components/ui/progress"; import {Textarea} from "@/components/ui/textarea";
import {createSubmission,listPublishedBooks} from "@/lib/supabase";
type Book={id:number;title:string;author:string;category:string;description:string;publicationYear:number;isbn:string;coverUrl:string;purchaseUrl:string}; type FormData=Record<string,string|boolean>;
const initial:FormData={authorName:"",email:"",phone:"",biography:"",title:"",subtitle:"",category:"",synopsis:"",audience:"",differentiator:"",stage:"",wordCount:"",rightsConfirmed:false,coverAvailable:false,reviewerOne:"",reviewerTwo:"",notes:""};
const steps=["Autoria","A obra","Viabilidade","Revisão"];
function LegacyHome(){
 const [books,setBooks]=useState<Book[]>([]),[query,setQuery]=useState(""),[step,setStep]=useState(0),[data,setData]=useState<FormData>(initial),[protocol,setProtocol]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false);
 useEffect(()=>{listPublishedBooks().then(setBooks).catch(()=>setBooks([]))},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool?:(tool:unknown,options?:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();context.registerTool({name:"start_editorial_submission",title:"Iniciar proposta editorial",description:"Abre o formulário de submissão de uma obra.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async()=>{document.querySelector("#publique")?.scrollIntoView({behavior:"smooth"});return{status:"form_opened"}}},{signal:lifecycle.signal});return()=>lifecycle.abort()},[]);
 const filtered=books.filter(b=>`${b.title} ${b.author} ${b.category}`.toLowerCase().includes(query.toLowerCase())); const set=(k:string,v:string|boolean)=>setData(x=>({...x,[k]:v})); const required=[["authorName","email","biography"],["title","category","synopsis"],["audience","differentiator","stage"],[]]; const canAdvance=required[step].every(k=>String(data[k]).trim());
 const summary=useMemo(()=>({Proponente:data.authorName||"—",Obra:[data.title,data.subtitle].filter(Boolean).join(" — ")||"—",Categoria:data.category||"—","Público":data.audience||"—","Estágio":data.stage||"—","Extensão":data.wordCount?`${data.wordCount} palavras`:"Não informada",Capa:data.coverAvailable?"Disponível":"Não disponível","Revisores sugeridos":[data.reviewerOne,data.reviewerTwo].filter(Boolean).join("; ")||"Não informados"}),[data]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!data.rightsConfirmed){setError("Confirme que você possui os direitos necessários para submeter a obra.");return}setSending(true);try{setProtocol(await createSubmission(data))}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar a proposta.")}finally{setSending(false)}}
 return <main><header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark">S</span><span><strong>Editora</strong><b>Sintechtica</b></span></a><nav><a href="#catalogo">Livros</a><a href="#publique">Publique conosco</a><a href="#processo">Como funciona</a></nav><Button asChild className="header-cta"><a href="#publique">Enviar original <ArrowRight size={16}/></a></Button></header>
 <section id="inicio" className="hero"><div className="eyebrow"><Sparkles size={15}/> Conhecimento que encontra leitores</div><h1>Ideias rigorosas.<br/><em>Livros relevantes.</em></h1><p>Publicamos obras que transformam conhecimento em impacto. Conheça nosso catálogo ou apresente seu original ao conselho editorial.</p><div className="hero-actions"><Button asChild size="lg"><a href="#catalogo"><BookOpen/> Explorar livros</a></Button><Button asChild size="lg" variant="outline"><a href="#publique"><FileText/> Submeter uma obra</a></Button></div><div className="hero-note"><span>01</span><p><strong>Curadoria editorial</strong>Avaliação estruturada, critérios claros e retorno responsável.</p></div></section>
 <section id="catalogo" className="section catalog"><div className="section-heading"><div><span>CATÁLOGO</span><h2>Livros publicados</h2></div><label className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por título, autor ou tema"/></label></div>{filtered.length?<div className="book-grid">{filtered.map((b,i)=><article className="book-card" key={b.id}><div className={`book-cover cover-${i%3}`} style={b.coverUrl?{backgroundImage:`url(${b.coverUrl})`}:{}}><span>{b.category}</span><b>{b.title}</b><small>{b.author}</small></div><div><span>{b.category} · {b.publicationYear}</span><h3>{b.title}</h3><p>{b.description}</p>{b.purchaseUrl&&<a href={b.purchaseUrl}>Conhecer o livro <ArrowRight size={15}/></a>}</div></article>)}</div>:<div className="empty-books"><BookOpen/><div><h3>Nosso catálogo está sendo preparado</h3><p>Os primeiros títulos aparecerão aqui assim que forem publicados.</p></div></div>}</section>
 <section id="processo" className="process section"><div><span>PROCESSO EDITORIAL</span><h2>Da proposta à decisão</h2><p>Uma submissão bem estruturada permite ao conselho analisar mérito, aderência e viabilidade sem perder tempo procurando informações essenciais.</p></div><ol>{["Envio da proposta","Triagem editorial","Avaliação do conselho","Retorno ao autor"].map((x,i)=><li key={x}><b>0{i+1}</b><span>{x}</span></li>)}</ol></section>
 <section id="publique" className="submission section"><div className="submission-intro"><span>SUBMISSÃO EDITORIAL</span><h2>Apresente sua obra</h2><p>Preencha as informações com objetividade. Ao final, você verá o mesmo resumo executivo que apoiará a primeira leitura do conselho.</p><div className="privacy"><Check/> Seus dados serão usados apenas no processo editorial.</div></div><Card className="form-card">{protocol?<div className="success"><span><Check/></span><h3>Proposta recebida</h3><p>Guarde o protocolo para acompanhar o contato da editora.</p><b>{protocol}</b><Button variant="outline" onClick={()=>{setProtocol("");setData(initial);setStep(0)}}>Enviar outra proposta</Button></div>:<form onSubmit={submit}><div className="form-top"><div><small>ETAPA {step+1} DE 4</small><h3>{steps[step]}</h3></div><span>{(step+1)*25}%</span></div><Progress value={(step+1)*25}/>
 {step===0&&<div className="fields"><Field label="Nome completo *"><Input value={String(data.authorName)} onChange={e=>set("authorName",e.target.value)}/></Field><div className="two"><Field label="E-mail *"><Input type="email" value={String(data.email)} onChange={e=>set("email",e.target.value)}/></Field><Field label="Telefone"><Input value={String(data.phone)} onChange={e=>set("phone",e.target.value)}/></Field></div><Field label="Mini currículo *" hint="Formação, experiência e relação com o tema."><Textarea value={String(data.biography)} onChange={e=>set("biography",e.target.value)}/></Field></div>}
 {step===1&&<div className="fields"><div className="two"><Field label="Título provisório *"><Input value={String(data.title)} onChange={e=>set("title",e.target.value)}/></Field><Field label="Subtítulo"><Input value={String(data.subtitle)} onChange={e=>set("subtitle",e.target.value)}/></Field></div><Field label="Área da obra *"><NativeSelect value={String(data.category)} onChange={e=>set("category",e.target.value)}><option value="">Selecione</option><option>Educação</option><option>Tecnologia</option><option>Gestão</option><option>Ciências Humanas</option><option>Literatura</option><option>Outra</option></NativeSelect></Field><Field label="Sinopse *" hint="Explique o tema, a abordagem e o que o leitor encontrará."><Textarea value={String(data.synopsis)} onChange={e=>set("synopsis",e.target.value)}/></Field></div>}
 {step===2&&<div className="fields"><Field label="Público-alvo *"><Input value={String(data.audience)} onChange={e=>set("audience",e.target.value)}/></Field><Field label="Diferencial da obra *" hint="O que ela acrescenta ao que já existe?"><Textarea value={String(data.differentiator)} onChange={e=>set("differentiator",e.target.value)}/></Field><div className="two"><Field label="Estágio do original *"><NativeSelect value={String(data.stage)} onChange={e=>set("stage",e.target.value)}><option value="">Selecione</option><option>Ideia estruturada</option><option>Em desenvolvimento</option><option>Original concluído</option><option>Original revisado</option></NativeSelect></Field><Field label="Número aproximado de palavras"><Input type="number" value={String(data.wordCount)} onChange={e=>set("wordCount",e.target.value)}/></Field></div><CheckField checked={Boolean(data.coverAvailable)} onChange={v=>set("coverAvailable",v)}>Já possuo uma proposta de capa</CheckField></div>}
 {step===3&&<div className="fields review"><div className="summary"><h4>Resumo para o conselho</h4>{Object.entries(summary).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}<div className="summary-long"><span>Sinopse</span><p>{String(data.synopsis)}</p></div><div className="summary-long"><span>Diferencial</span><p>{String(data.differentiator)}</p></div></div><div className="two"><Field label="Revisor sugerido 1"><Input value={String(data.reviewerOne)} onChange={e=>set("reviewerOne",e.target.value)} placeholder="Nome e vínculo"/></Field><Field label="Revisor sugerido 2"><Input value={String(data.reviewerTwo)} onChange={e=>set("reviewerTwo",e.target.value)} placeholder="Nome e vínculo"/></Field></div><Field label="Observações adicionais"><Textarea value={String(data.notes)} onChange={e=>set("notes",e.target.value)}/></Field><CheckField checked={Boolean(data.rightsConfirmed)} onChange={v=>set("rightsConfirmed",v)}>Declaro que tenho os direitos necessários para submeter esta obra. *</CheckField></div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft/> Voltar</Button>{step<3?<Button type="button" disabled={!canAdvance} onClick={()=>setStep(s=>s+1)}>Continuar <ChevronRight/></Button>:<Button type="submit" disabled={sending}>{sending?"Enviando…":"Enviar ao conselho"} <ArrowRight/></Button>}</div></form>}</Card></section>
 <footer><a className="brand" href="#inicio"><span className="brand-mark">S</span><span><strong>Editora</strong><b>Sintechtica</b></span></a><p>Conhecimento com rigor, clareza e propósito.</p><span>© {new Date().getFullYear()} Editora Sintechtica</span></footer></main>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}; function CheckField({checked,onChange,children}:{checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode}){return <label className="check-field"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
