"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,BookOpen,Check,ChevronLeft,ChevronRight,FileText,Search,Sparkles} from "lucide-react";
import {Button} from "@/components/ui/button"; import {Card} from "@/components/ui/card"; import {Checkbox} from "@/components/ui/checkbox"; import {Input} from "@/components/ui/input"; import {NativeSelect} from "@/components/ui/native-select"; import {Progress} from "@/components/ui/progress"; import {Textarea} from "@/components/ui/textarea";
import {createEditorialSubmission,listPublishedBooks} from "@/lib/supabase";
type Book={id:number;title:string;author:string;category:string;description:string;publicationYear:number;isbn:string;coverUrl:string;purchaseUrl:string}; type FormData=Record<string,string|boolean>;
const initial:FormData={scopeConfirmed:"",authorName:"",email:"",phone:"",institution:"",department:"",cineAreas:"",workAuthors:"",workType:"",pageCount:"",relevance:"",originality:"",reach:"",collectionFit:"",presentation:"",tableOfContents:"",audiences:"",editorialFit:"",neurolearning:"",visualIdentity:"",reviewerOne:"",reviewerTwo:"",bibliographicReferences:"",authorshipConfirmed:false,publicationAuthorized:false,imageRightsConfirmed:false,aiUseConfirmed:false,rightsConfirmed:false};
const steps=["Identificação","Dados da obra","Síntese estratégica","Aderência e público","Arquivos e revisão"];
const cineOptions=["Agricultura, silvicultura, pesca e veterinária","Artes e humanidades","Ciências naturais, matemática e estatística","Ciências sociais, comunicação e informação","Computação e Tecnologias da Informação e Comunicação (TIC)","Educação","Engenharia, produção e construção","Negócios, administração e direito","Saúde e bem-estar","Serviços"];
const audienceOptions=["Estudantes de graduação","Estudantes de pós-graduação","Docentes","Pesquisadores","Profissionais","Gestores","Público geral","Outra"];
const workTypes=["I. E-books vinculados aos materiais didáticos das unidades curriculares","II. Livros acadêmicos e científicos","III. Coletâneas e obras organizadas","IV. Anais de eventos acadêmicos e científicos","V. Obras decorrentes de pesquisas e projetos institucionais","VI. Relatos e sistematizações de experiências acadêmicas e docentes","VII. Obras acadêmicas de interesse estratégico do Ecossistema Ânima","VIII. Outras publicações acadêmicas, científicas ou institucionais compatíveis com o escopo"];
export default function Site(){
 const [books,setBooks]=useState<Book[]>([]),[query,setQuery]=useState(""),[step,setStep]=useState(0),[data,setData]=useState<FormData>(initial),[protocol,setProtocol]=useState(""),[error,setError]=useState(""),[sending,setSending]=useState(false),[manuscript,setManuscript]=useState<File|null>(null);
 useEffect(()=>{listPublishedBooks().then(setBooks).catch(()=>setBooks([]))},[]);
 const filtered=books.filter(b=>[b.title,b.author,b.category].join(" ").toLowerCase().includes(query.toLowerCase())); const set=(k:string,v:string|boolean)=>setData(x=>({...x,[k]:v}));
 const toggle=(k:string,v:string)=>{const values=String(data[k]||"").split("|").filter(Boolean);set(k,values.includes(v)?values.filter(x=>x!==v).join("|"):[...values,v].join("|"))}; const has=(k:string,v:string)=>String(data[k]||"").split("|").includes(v);
 const required=[["scopeConfirmed","authorName","email","phone","institution","department"],["cineAreas","workAuthors","workType","pageCount"],["relevance","originality","reach","collectionFit","presentation","tableOfContents"],["audiences","editorialFit","visualIdentity"],["bibliographicReferences"]]; const canAdvance=required[step].every(k=>String(data[k]).trim())&&(step!==0||data.scopeConfirmed==="Sim");
 const summary=useMemo(()=>({"Questão 7 · Área CINE":String(data.cineAreas||"—").replaceAll("|",", "),"Questão 9 · Tipo de obra":data.workType||"—","Questão 11 · Relevância":data.relevance||"—","Questão 12 · Originalidade e contribuição":data.originality||"—","Questão 13 · Potencial de alcance":data.reach||"—","Questão 14 · Pertinência ao acervo":data.collectionFit||"—","Questão 16 · Descrição do sumário":data.tableOfContents||"—","Questão 17 · Público-alvo":String(data.audiences||"—").replaceAll("|",", "),"Questão 22 · Referências bibliográficas":data.bibliographicReferences||"—"}),[data]);
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!manuscript){setError("Anexe a obra completa em Word.");return}const declarations=[data.authorshipConfirmed,data.publicationAuthorized,data.imageRightsConfirmed,data.aiUseConfirmed];if(declarations.some(value=>value!==true)){setError("É necessário concordar com as declarações das questões 24 a 27.");return}setSending(true);try{setProtocol(await createEditorialSubmission({...data,rightsConfirmed:true},manuscript))}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar a proposta.")}finally{setSending(false)}}
 const reset=()=>{setProtocol("");setData(initial);setStep(0);setManuscript(null)};
 return <main><header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark">S</span><span><strong>Editora</strong><b>Sintechtica</b></span></a><nav><a href="#catalogo">Livros</a><a href="#publique">Publique conosco</a><a href="#processo">Como funciona</a></nav><Button asChild className="header-cta"><a href="#publique">Enviar original <ArrowRight size={16}/></a></Button></header>
 <section id="inicio" className="hero"><div className="eyebrow"><Sparkles size={15}/> Conhecimento que encontra leitores</div><h1>Ideias rigorosas.<br/><em>Livros relevantes.</em></h1><p>Publicamos obras que transformam conhecimento em impacto. Conheça nosso catálogo ou apresente seu original ao conselho editorial.</p><div className="hero-actions"><Button asChild size="lg"><a href="#catalogo"><BookOpen/> Explorar livros</a></Button><Button asChild size="lg" variant="outline"><a href="#publique"><FileText/> Submeter uma obra</a></Button></div><div className="hero-note"><span>01</span><p><strong>Curadoria editorial</strong>Avaliação estruturada, critérios claros e retorno responsável.</p></div></section>
 <section id="catalogo" className="section catalog"><div className="section-heading"><div><span>CATÁLOGO</span><h2>Livros publicados</h2></div><label className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por título, autor ou tema"/></label></div>{filtered.length?<div className="book-grid">{filtered.map((b,i)=><article className="book-card" key={b.id}><div className={"book-cover cover-"+i%3} style={b.coverUrl?{backgroundImage:"url("+b.coverUrl+")"}:{}}><span>{b.category}</span><b>{b.title}</b><small>{b.author}</small></div><div><span>{b.category} · {b.publicationYear}</span><h3>{b.title}</h3><p>{b.description}</p>{b.purchaseUrl&&<a href={b.purchaseUrl}>Conhecer o livro <ArrowRight size={15}/></a>}</div></article>)}</div>:<div className="empty-books"><BookOpen/><div><h3>Nosso catálogo está sendo preparado</h3><p>Os primeiros títulos aparecerão aqui assim que forem publicados.</p></div></div>}</section>
 <section id="processo" className="process section"><div><span>PROCESSO EDITORIAL</span><h2>Da proposta à decisão</h2><p>As respostas geram uma síntese estruturada para apoiar a avaliação do Conselho Editorial.</p></div><ol>{["Envio da proposta","Triagem editorial","Avaliação do conselho","Retorno ao autor"].map((x,i)=><li key={x}><b>0{i+1}</b><span>{x}</span></li>)}</ol></section>
 <section id="publique" className="submission section"><div className="submission-intro"><span>SUBMISSÃO EDITORIAL</span><h2>Apresente sua obra</h2><p>Preencha todos os campos obrigatórios, anexe o original completo e confirme as declarações de responsabilidade.</p><div className="privacy"><Check/> Dados usados exclusivamente no processo editorial.</div></div><Card className="form-card">{protocol?<div className="success"><span><Check/></span><h3>Proposta recebida</h3><p>Guarde o protocolo para acompanhar o contato da editora.</p><b>{protocol}</b><Button variant="outline" onClick={reset}>Enviar outra proposta</Button></div>:<form onSubmit={submit}><div className="form-top"><div><small>ETAPA {step+1} DE 5</small><h3>{steps[step]}</h3></div><span>{(step+1)*20}%</span></div><Progress value={(step+1)*20}/>
 {step===0&&<div className="fields"><Field label="1. Seu projeto está dentro do escopo editorial da Editora Sintechtica? *"><NativeSelect value={String(data.scopeConfirmed)} onChange={e=>set("scopeConfirmed",e.target.value)}><option value="">Selecione</option><option>Sim</option><option>Não</option></NativeSelect></Field>{data.scopeConfirmed==="Não"&&<p className="form-error">A submissão só pode prosseguir quando a proposta estiver dentro do escopo editorial.</p>}<Field label="2. Nome completo *"><Input value={String(data.authorName)} onChange={e=>set("authorName",e.target.value)}/></Field><div className="two"><Field label="3. E-mail *"><Input type="email" value={String(data.email)} onChange={e=>set("email",e.target.value)}/></Field><Field label="4. Telefone com DDD *"><Input inputMode="tel" value={String(data.phone)} onChange={e=>set("phone",e.target.value)}/></Field></div><div className="two"><Field label="5. IES de vínculo *"><Input value={String(data.institution)} onChange={e=>set("institution",e.target.value)} placeholder="Ex.: UNIFACS"/></Field><Field label="6. Área/Diretoria de atuação *"><Input value={String(data.department)} onChange={e=>set("department",e.target.value)}/></Field></div></div>}
 {step===1&&<div className="fields"><MultiField label="7. Área do conhecimento (CINE) *" options={cineOptions} selected={v=>has("cineAreas",v)} toggle={v=>toggle("cineAreas",v)}/><Field label="8. Nome completo do(s) autor(es) da obra *"><Textarea value={String(data.workAuthors)} onChange={e=>set("workAuthors",e.target.value)}/></Field><Field label="9. Tipo de obra *"><NativeSelect value={String(data.workType)} onChange={e=>set("workType",e.target.value)}><option value="">Selecione</option>{workTypes.map(x=><option key={x}>{x}</option>)}</NativeSelect></Field><Field label="10. Número estimado de páginas *"><Input type="number" min="1" value={String(data.pageCount)} onChange={e=>set("pageCount",e.target.value)}/></Field></div>}
 {step===2&&<div className="fields"><p><strong>Síntese estratégica da obra</strong><br/>Apresente elementos objetivos que apoiem a apreciação pelo Conselho Editorial.</p><Field label="11. Relevância *"><Textarea value={String(data.relevance)} onChange={e=>set("relevance",e.target.value)}/></Field><Field label="12. Originalidade e contribuição *"><Textarea value={String(data.originality)} onChange={e=>set("originality",e.target.value)}/></Field><Field label="13. Potencial de alcance *"><Textarea value={String(data.reach)} onChange={e=>set("reach",e.target.value)}/></Field><Field label="14. Pertinência para o acervo do Ecossistema Ânima *"><Textarea value={String(data.collectionFit)} onChange={e=>set("collectionFit",e.target.value)}/></Field><Field label="15. Apresentação da obra *" hint="Comece com “Título da obra:” e apresente tema central, objetivos, abordagem e principais conteúdos."><Textarea value={String(data.presentation)} onChange={e=>set("presentation",e.target.value)}/></Field><Field label="16. Descrição do sumário *" hint="Estrutura, capítulos/seções e conteúdos de cada parte."><Textarea value={String(data.tableOfContents)} onChange={e=>set("tableOfContents",e.target.value)}/></Field></div>}
 {step===3&&<div className="fields"><MultiField label="17. Público-alvo *" options={audienceOptions} selected={v=>has("audiences",v)} toggle={v=>toggle("audiences",v)}/><Field label="18. Aderência à linha editorial da Sintechtica *"><Textarea value={String(data.editorialFit)} onChange={e=>set("editorialFit",e.target.value)}/></Field><Field label="19. Conexão com os domínios da Taxonomia da Neuroaprendizagem" hint="Pergunta não obrigatória."><Textarea value={String(data.neurolearning)} onChange={e=>set("neurolearning",e.target.value)}/></Field><Field label="20. Layout e identidade visual esperados *"><Textarea value={String(data.visualIdentity)} onChange={e=>set("visualIdentity",e.target.value)}/></Field></div>}
 {step===4&&<div className="fields review"><div className="two"><Field label="21. Revisor especialista sugerido 1" hint="Opcional"><Input value={String(data.reviewerOne)} onChange={e=>set("reviewerOne",e.target.value)} placeholder="Colaborador Ânima"/></Field><Field label="21. Revisor especialista sugerido 2" hint="Opcional"><Input value={String(data.reviewerTwo)} onChange={e=>set("reviewerTwo",e.target.value)} placeholder="Colaborador Ânima"/></Field></div><Field label="22. Referências bibliográficas utilizadas na obra *"><Textarea value={String(data.bibliographicReferences)} onChange={e=>set("bibliographicReferences",e.target.value)}/></Field><Field label="23. Obra na íntegra em Word *" hint="Fonte Arial 12, espaçamento 1,5, texto justificado e páginas numeradas."><Input type="file" accept=".doc,.docx" onChange={e=>setManuscript(e.target.files?.[0]||null)}/></Field><CheckField checked={Boolean(data.authorshipConfirmed)} onChange={v=>set("authorshipConfirmed",v)}>24. Declaro que sou autor(a) ou responsável autorizado(a), que a obra é original, não contém plágio e não viola direitos de terceiros. *</CheckField><CheckField checked={Boolean(data.publicationAuthorized)} onChange={v=>set("publicationAuthorized",v)}>25. Declaro possuir as autorizações necessárias e autorizo a submissão, edição e publicação da obra, caso aprovada. *</CheckField><CheckField checked={Boolean(data.imageRightsConfirmed)} onChange={v=>set("imageRightsConfirmed",v)}>26. Declaro possuir autorização para conteúdos de terceiros eventualmente incluídos na obra. *</CheckField><CheckField checked={Boolean(data.aiUseConfirmed)} onChange={v=>set("aiUseConfirmed",v)}>27. Declaro que eventual uso de IA ocorreu de forma responsável e permanece sob minha responsabilidade. *</CheckField><div className="summary"><h4>Conteúdo do PDF para o Conselho Editorial</h4>{Object.entries(summary).map(([k,v])=><div className="summary-long" key={k}><span>{k}</span><p>{String(v)}</p></div>)}</div></div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" variant="ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ChevronLeft/> Voltar</Button>{step<4?<Button type="button" disabled={!canAdvance} onClick={()=>setStep(s=>s+1)}>Continuar <ChevronRight/></Button>:<Button type="submit" disabled={sending||!canAdvance}>{sending?"Enviando…":"Enviar ao conselho"} <ArrowRight/></Button>}</div></form>}</Card></section>
 <footer><a className="brand" href="#inicio"><span className="brand-mark">S</span><span><strong>Editora</strong><b>Sintechtica</b></span></a><p>Conhecimento com rigor, clareza e propósito.</p><a href="#admin">Área administrativa</a><span>© {new Date().getFullYear()} Editora Sintechtica</span></footer></main>}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function CheckField({checked,onChange,children}:{checked:boolean;onChange:(v:boolean)=>void;children:React.ReactNode}){return <label className="check-field"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
function MultiField({label,options,selected,toggle}:{label:string;options:string[];selected:(v:string)=>boolean;toggle:(v:string)=>void}){return <fieldset className="field"><legend>{label}</legend><div className="fields">{options.map(x=><CheckField key={x} checked={selected(x)} onChange={()=>toggle(x)}>{x}</CheckField>)}</div></fieldset>}
