import {Upload} from "tus-js-client";
type Payload=Record<string,string|boolean>;
const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"")??"";
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";
const headers={apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"};
function configured(){if(!url||!key)throw new Error("A conexão com o Supabase ainda não foi configurada.")}
export async function listPublishedBooks(){configured();const r=await fetch(`${url}/rest/v1/books?published=eq.true&select=id,title,author,category,description,publication_year,isbn,cover_url,purchase_url&order=publication_year.desc,id.desc`,{headers,cache:"no-store"});if(!r.ok)throw new Error("Catálogo temporariamente indisponível.");return(await r.json()).map((b:Record<string,unknown>)=>({id:b.id,title:b.title,author:b.author,category:b.category,description:b.description,publicationYear:b.publication_year,isbn:b.isbn,coverUrl:b.cover_url,purchaseUrl:b.purchase_url}))}
export async function createSubmission(data:Payload){configured();const protocol=`SIN-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const clean=(k:string)=>String(data[k]??"").trim().slice(0,6000);const body={protocol,author_name:clean("authorName"),email:clean("email"),phone:clean("phone"),biography:clean("biography"),title:clean("title"),subtitle:clean("subtitle"),category:clean("category"),synopsis:clean("synopsis"),audience:clean("audience"),differentiator:clean("differentiator"),stage:clean("stage"),word_count:clean("wordCount"),rights_confirmed:data.rightsConfirmed===true,cover_available:data.coverAvailable===true,reviewer_one:clean("reviewerOne"),reviewer_two:clean("reviewerTwo"),notes:clean("notes")};const r=await fetch(`${url}/rest/v1/submissions`,{method:"POST",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Não foi possível registrar a proposta agora. Revise os campos e tente novamente.");return protocol}

async function uploadEditorialFile(file:File,protocol:string,kind:string){
 const ext=file.name.split(".").pop()?.toLowerCase()||"bin"; const path=protocol+"/"+kind+"."+ext;
 return new Promise<string>((resolve,reject)=>{
  const upload=new Upload(file,{endpoint:url+"/storage/v1/upload/resumable",retryDelays:[0,3000,5000,10000,20000],headers:{authorization:"Bearer "+key,apikey:key},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:"editorial-submissions",objectName:path,contentType:file.type||"application/octet-stream",cacheControl:"3600"},onError:()=>reject(new Error("Não foi possível enviar o arquivo: "+file.name)),onSuccess:()=>resolve(path)});
  upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()}).catch(()=>upload.start());
 });
}
export async function createEditorialSubmission(data:Payload,manuscript:File,rightsFile:File){configured();const protocol="SIN-"+new Date().getFullYear()+"-"+crypto.randomUUID().slice(0,8).toUpperCase();const clean=(k:string)=>String(data[k]??"").trim().slice(0,12000);const manuscriptPath=await uploadEditorialFile(manuscript,protocol,"obra");const rightsPath=await uploadEditorialFile(rightsFile,protocol,"termo-direitos");const body={protocol,scope_confirmed:clean("scopeConfirmed")==="Sim",author_name:clean("authorName"),email:clean("email"),phone:clean("phone"),institution:clean("institution"),department:clean("department"),cine_areas:clean("cineAreas"),work_authors:clean("workAuthors"),work_type:clean("workType"),page_count:Number(clean("pageCount")),relevance:clean("relevance"),originality:clean("originality"),reach:clean("reach"),collection_fit:clean("collectionFit"),work_title:clean("workTitle"),presentation:clean("presentation"),table_of_contents:clean("tableOfContents"),audiences:clean("audiences"),editorial_fit:clean("editorialFit"),neurolearning:clean("neurolearning"),visual_identity:clean("visualIdentity"),reviewer_one:clean("reviewerOne"),reviewer_two:clean("reviewerTwo"),manuscript_path:manuscriptPath,rights_file_path:rightsPath,rights_confirmed:data.rightsConfirmed===true,status:"recebida"};const r=await fetch(url+"/rest/v1/editorial_submissions",{method:"POST",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Os arquivos foram enviados, mas a proposta não foi registrada. Informe o protocolo "+protocol+" à gestão editorial.");fetch(url+"/functions/v1/notify-editorial-submission",{method:"POST",headers,body:JSON.stringify({protocol})}).catch(()=>undefined);return protocol}

export type EditorialSubmission={id:number;protocol:string;author_name:string;email:string;phone:string;institution:string;department:string;cine_areas:string;work_authors:string;work_type:string;page_count:number;relevance:string;originality:string;reach:string;collection_fit:string;work_title:string;presentation:string;table_of_contents:string;audiences:string;editorial_fit:string;neurolearning:string;visual_identity:string;reviewer_one:string;reviewer_two:string;manuscript_path:string;rights_file_path:string;status:string;created_at:string;email_sent_at:string|null};
const sessionKey="sintechtica_admin_session";
export function getAdminSession(){if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(sessionKey)||"null") as {access_token:string;refresh_token:string;expires_at:number;user:{email:string}}|null}catch{return null}}
export async function adminLogin(email:string,password:string){configured();const r=await fetch(url+"/auth/v1/token?grant_type=password",{method:"POST",headers,body:JSON.stringify({email,password})});const body=await r.json();if(!r.ok)throw new Error(body.error_description||body.msg||"E-mail ou senha inválidos.");const session={access_token:body.access_token,refresh_token:body.refresh_token,expires_at:Math.floor(Date.now()/1000)+body.expires_in,user:body.user};localStorage.setItem(sessionKey,JSON.stringify(session));return session}
export async function adminLogout(){const session=getAdminSession();if(session)await fetch(url+"/auth/v1/logout",{method:"POST",headers:{...headers,Authorization:"Bearer "+session.access_token}}).catch(()=>undefined);localStorage.removeItem(sessionKey)}
function adminHeaders(){const session=getAdminSession();if(!session)throw new Error("Faça login novamente.");return {...headers,Authorization:"Bearer "+session.access_token}}
export async function listEditorialSubmissions(){configured();const r=await fetch(url+"/rest/v1/editorial_submissions?select=*&order=created_at.desc",{headers:adminHeaders(),cache:"no-store"});if(r.status===401)throw new Error("Sua sessão expirou. Faça login novamente.");if(!r.ok)throw new Error("Você não possui acesso administrativo.");return await r.json() as EditorialSubmission[]}
export async function updateEditorialStatus(id:number,status:string){const r=await fetch(url+`/rest/v1/editorial_submissions?id=eq.${id}`,{method:"PATCH",headers:{...adminHeaders(),Prefer:"return=minimal"},body:JSON.stringify({status})});if(!r.ok)throw new Error("Não foi possível atualizar o status.")}
export async function createEditorialDownload(path:string){const r=await fetch(url+"/storage/v1/object/sign/editorial-submissions/"+path.split("/").map(encodeURIComponent).join("/"),{method:"POST",headers:adminHeaders(),body:JSON.stringify({expiresIn:300})});const body=await r.json();if(!r.ok||!body.signedURL)throw new Error("Não foi possível liberar o arquivo.");return url+"/storage/v1"+body.signedURL}
