import {Upload} from "tus-js-client";
type Payload=Record<string,string|boolean>;
const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"")??"";
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY??"";
const headers={apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"};
function configured(){if(!url||!key)throw new Error("A conexão com o Supabase ainda não foi configurada.")}
export async function listPublishedBooks(){configured();const r=await fetch(`${url}/rest/v1/books?published=eq.true&select=id,title,author,category,description,publication_year,isbn,cover_url,purchase_url&order=publication_year.desc,id.desc`,{headers,cache:"no-store"});if(!r.ok)throw new Error("Catálogo temporariamente indisponível.");return(await r.json()).map((b:Record<string,unknown>)=>({id:b.id,title:b.title,author:b.author,category:b.category,description:b.description,publicationYear:b.publication_year,isbn:b.isbn,coverUrl:b.cover_url,purchaseUrl:b.purchase_url}))}
export async function createSubmission(data:Payload){configured();const protocol=`SIN-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const clean=(k:string)=>String(data[k]??"").trim().slice(0,6000);const body={protocol,author_name:clean("authorName"),email:clean("email"),phone:clean("phone"),biography:clean("biography"),title:clean("title"),subtitle:clean("subtitle"),category:clean("category"),synopsis:clean("synopsis"),audience:clean("audience"),differentiator:clean("differentiator"),stage:clean("stage"),word_count:clean("wordCount"),rights_confirmed:data.rightsConfirmed===true,cover_available:data.coverAvailable===true,reviewer_one:clean("reviewerOne"),reviewer_two:clean("reviewerTwo"),notes:clean("notes")};const r=await fetch(`${url}/rest/v1/submissions`,{method:"POST",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Não foi possível registrar a proposta agora. Revise os campos e tente novamente.");return protocol}

async function uploadEditorialFile(file:File,protocol:string,kind:string){
 const ext=file.name.split(".").pop()?.toLowerCase()||"bin"; const path=protocol+"/"+kind+"."+ext;
 return new Promise<string>((resolve,reject)=>{
  const upload=new Upload(file,{endpoint:url+"/storage/v1/upload/resumable",retryDelays:[0,3000,5000,10000,20000],headers:{authorization:"Bearer "+key,apikey:key},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:"editorial-submissions",objectName:path,contentType:file.type||"application/octet-stream",cacheControl:"3600"},onError:()=>reject(new Error("Não foi possível enviar o arquivo: "+file.name)),onSuccess:()=>resolve(path)});
  upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()}).catch(()=>upload.start());
 });
}
export async function createEditorialSubmission(data:Payload,manuscript:File,rightsFile:File){configured();const protocol="SIN-"+new Date().getFullYear()+"-"+crypto.randomUUID().slice(0,8).toUpperCase();const clean=(k:string)=>String(data[k]??"").trim().slice(0,12000);const manuscriptPath=await uploadEditorialFile(manuscript,protocol,"obra");const rightsPath=await uploadEditorialFile(rightsFile,protocol,"termo-direitos");const body={protocol,scope_confirmed:clean("scopeConfirmed")==="Sim",author_name:clean("authorName"),email:clean("email"),phone:clean("phone"),institution:clean("institution"),department:clean("department"),cine_areas:clean("cineAreas"),work_authors:clean("workAuthors"),work_type:clean("workType"),page_count:Number(clean("pageCount")),relevance:clean("relevance"),originality:clean("originality"),reach:clean("reach"),collection_fit:clean("collectionFit"),work_title:clean("workTitle"),presentation:clean("presentation"),table_of_contents:clean("tableOfContents"),audiences:clean("audiences"),editorial_fit:clean("editorialFit"),neurolearning:clean("neurolearning"),visual_identity:clean("visualIdentity"),reviewer_one:clean("reviewerOne"),reviewer_two:clean("reviewerTwo"),manuscript_path:manuscriptPath,rights_file_path:rightsPath,rights_confirmed:data.rightsConfirmed===true,status:"recebida"};const r=await fetch(url+"/rest/v1/editorial_submissions",{method:"POST",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok)throw new Error("Os arquivos foram enviados, mas a proposta não foi registrada. Informe o protocolo "+protocol+" à gestão editorial.");return protocol}
